### ISSUE TITLE
`conditional-flows` rule on multiple outgoing flows with no conditions

### ISSUE THREAD

**Issue by deanmzamzow** [bpmn-io/bpmnlint#130]
### Describe the Bug

The `conditional-flows` rule should invalidate flows when:
* the source node is exclusive or inclusive gateway
* the source node has more than one flow
* none of the source node's outgoing flows has a condition, nor does the source node have a default node

Currently, the rule does not invalidate these flows. However, on submitting the bpmn to Camunda, it is disallowed with response `"Must have a condition or be default flow"` for each outgoing flow of the exclusive or inclusive gateway.

### Steps to Reproduce

Run the `conditional-flows` rule against a bpmn model with the following:

```xml
  <bpmn:process id="Process" isExecutable="true">
    <bpmn:exclusiveGateway id="Source">
      <bpmn:outgoing>Flow_1</bpmn:outgoing>
      <bpmn:outgoing>Flow_2</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:intermediateThrowEvent id="Target_1">
      <bpmn:incoming>Flow_1</bpmn:incoming>
    </bpmn:intermediateThrowEvent>
    <bpmn:sequenceFlow id="Flow_1" sourceRef="Source" targetRef="Target_1" />
    <bpmn:intermediateThrowEvent id="Target_2">
      <bpmn:incoming>Flow_2</bpmn:incoming>
    </bpmn:intermediateThrowEvent>
    <bpmn:sequenceFlow id="Flow_2" sourceRef="Source" targetRef="Target_2" />
  </bpmn:process>
```
![image](https://github.com/bpmn-io/bpmnlint/assets/159582363/f45381f3-e08a-4c9d-9bb1-040b365faf38)

### Expected Behavior

Each flow with no condition should be invalid even when all flows do not have a condition.

### Environment
- Library version: 9.2.0

**Comment by nikku** [comment]
Thanks for opening this issue! Let's examine what [the rule does](https://github.com/bpmn-io/bpmnlint/blob/main/docs/rules/conditional-flows.md):

> Ensures that conditions on sequence flows are consistently set. If a sequence flow outgoing from a conditional forking gateway or activity is default or any sequence flow has a condition attached, all others have to have to have respective condition meta-data attached, too.

In other words: If a user adds at least _one_ condition or default flow _then_ all of the respective flows must have a condition (or be default). On the other hand, if I decide to not add a condition at all (because I'm in modeling only, not for execution mode) then the diagram validates just fine. Focus is on `consistently` here.

Did you find a situation where what the rule does violates the constraint? If I understand you correctly then you want the rule to be more rigid. This would make it report tons of cases where folks happily use BPMN as a language to communicate process knowledge with no intend of implementing it.

**Comment by deanmzamzow** [comment]
I understand - I do want a more rigid rule, for the purpose of validating a diagram for execution.

If you like, I can create a separate rule for this validation. Otherwise, I can create such a rule in my local rule set instead.

**Comment by nikku** [comment]
What execution platform do you target?

**Comment by deanmzamzow** [comment]
We deploy these bpmn models to cloud-hosted operate.camunda.io for execution. Does that answer the question?

**Comment by nikku** [comment]
If your engine is Camunda 8, then I'd ask you to checkout [bpmnlint-plugin-camunda-compat](https://github.com/camunda/bpmnlint-plugin-camunda-compat), an extension that validates your diagrams against Camunda 8 "readyness for execution".

**Comment by nikku** [comment]
I'm closing this issue as won't fix.
